# -*- coding: utf-8 -*-
"""(EDA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1POtsIL2-JeZH14AU7uQThLECxkIHcrf6

Dara file
https://www.kaggle.com/datasets/jainaru/thyroid-disease-data/code

import file
"""

#(หน้าที่)ฟาต้องนำเข้าข้อมูล
from google.colab import files
uploaded = files.upload()
import pandas as pd
df = pd.read_csv("Thyroid_Diff.csv")
print(df.head())

"""Check and clean dataframe"""

df.describe()

df.shape

import numpy as np

print(df.isna().sum())

#(หน้าที่)ฟาต้องดูcolumnที่น่าใช้
df.info()

"""Filter data"""

#ดูความสัมพันธ์ของทุกอัน
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

cols = df.select_dtypes(include=['object']).columns
encoded = pd.get_dummies(df, columns=cols)
corr_encoded = encoded.corr()

plt.figure(figsize=(30, 25)) # Increased figure size
sns.heatmap(corr_encoded, annot=True, cmap='coolwarm', fmt=".2f")
plt.show()

"""visualizetion"""

#การกระจายอายุของผู้ป่วย
plt.figure(figsize=(8, 6))
sns.histplot(x='Age',data=df , kde=True)
plt.title('Age Distribution of Patients')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

#ความสัมพันธ์ระหว่างอายุกับระยะการเกิดโรค
sns.boxplot(x='Stage', y='Age', data=df)
plt.title("Age vs. Cancer Stage")
plt.show()

#การกระจายของอายุ (Age) ตาม ระดับความเสี่ยงของโรค
plt.figure(figsize=(14, 8))
sns.violinplot(x='Risk', y='Age', data=df, palette='OrRd', inner='quartile')
plt.title('Distribution of Ages by Risk Category')
plt.xlabel('Risk Category')
plt.ylabel('Age')
plt.show()

#จำนวนผู้ป่วยแต่ละเพศ
plt.figure(figsize=(8, 6))
sns.countplot(x='Gender', data=df)
plt.title('Gender Distribution')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()

#การกระจายของ สถานะการสูบบุหรี่
plt.figure(figsize=(8, 6))
sns.countplot(x='Smoking', data=df)
plt.title('Smoking Status Distribution')
plt.xlabel('Smoking Status')
plt.ylabel('Count')
plt.show()

#การกระจายของชนิดมะเร็ง
plt.figure(figsize=(8, 6))
sns.countplot(x='Pathology', data=df, palette='viridis')
plt.title('Cancer Type Distribution')
plt.xlabel('Pathology')
plt.ylabel('Count')
plt.show()

#ความสัมพันธ์ระหว่างลักษณะก้อนมะเร็งกับระดับความเสี่ยงของโรค
plt.figure(figsize=(8, 6))
sns.countplot(x='Focality', hue='Risk', data=df)
plt.title('Focality vs. Risk Category')
plt.xlabel('Focality')
plt.ylabel('Count')
plt.legend(title='Risk Category')
plt.show()

#ระยะโรคมะเร็ง
plt.figure(figsize=(8, 6))
sns.countplot(x='Stage', data=df)
plt.title('Stage Distribution')
plt.xlabel('Stage')
plt.ylabel('Count')
plt.show()

#ความสัมพันธ์ระหว่างผลการตอบสนองต่อการรักษา กับ การกลับมาเป็นซ้ำของโรค
#ฟาในอดีตสนใจอันนี้
plt.figure(figsize=(10, 6))
sns.countplot(x='Response', hue='Recurred', data=df)
plt.title('Response to Treatment vs. Recurrence')
plt.xlabel('Response to Treatment')
plt.ylabel('Count')
plt.legend(title='Recurred')
plt.show()
prop = pd.crosstab(df['Response'], df['Recurred'], normalize='index') * 100
print(prop)
plt.figure(figsize=(8,6))
prop_yes = prop['Yes']
prop_yes = prop_yes.reindex(df['Response'].unique())
prop_yes.plot(kind='bar', color='red')
plt.title("Proportion of Recurrence (Yes) by 'Response")
plt.ylabel("Percentage of Recurrence (%)")
plt.xlabel("'Response")
plt.show()

#สัมพันธ์ของชนิดของมะเร็งกับโอกาสการกลับมาเป็นซ้ำ
#ฟาในอดีตสนใจอันนี้
sns.countplot(x='Pathology', hue='Recurred', data=df)
plt.title("Cancer Type vs. Recurrence")
plt.show()
prop = pd.crosstab(df['Pathology'], df['Recurred'], normalize='index') * 100
print(prop)
plt.figure(figsize=(8,6))
prop_yes = prop['Yes']
prop_yes = prop_yes.reindex(df['Pathology'].unique())
prop_yes.plot(kind='bar', color='red')
plt.title("Proportion of Recurrence (Yes) by Cancer Type")
plt.ylabel("Percentage of Recurrence (%)")
plt.xlabel("Cancer Type (Pathology)")
plt.show()